### PR TITLE
#316 fix exported job

### LINKED ISSUE #316: Fix job xml shape when exporting it
When exporting a job in debug mode (and for SA) the xml is not compliant with the xsd. A test will be added too

### PR DESCRIPTION
**Pull request by marcochiaramello**
Closes #316

### CODE REVIEW

File: tests/outputs/TestJob.cpp [hunk 1]
```diff
@@ -87,4 +87,26 @@ TEST(Job, write) {
...
+  boost::filesystem::path outputPath(outputPathResults);
+  outputPath.append(basename);
+  if (!boost::filesystem::exists(outputPath)) {
+    boost::filesystem::create_directories(outputPath);
+  }
+  job.exportJob(jobEntry, "TestIIDM.iidm", outputPath);
+
+  boost::filesystem::path reference("reference");
+  reference.append(basename);
+  reference.append(filename_reference);
```
Comment (rosiereflo) [inline tests/outputs/TestJob.cpp:108]: Maybe we could add a call to xmlint to validate the scheme as this file might evolve without being tested in dynawo?

File: tests/outputs/reference/TestJob/TestJob_debug.jobs [hunk 2]
```diff
@@ -0,0 +1,21 @@
+<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
```
Comment (rosiereflo) [inline tests/outputs/reference/TestJob/TestJob_debug.jobs:1]: missing copyright

**Review by rosiereflo — CHANGES_REQUESTED** [review]

**Review by rosiereflo — APPROVED** [review]
